apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-wait
  labels:
    app: nginx-wait
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-wait
  template:
    metadata:
      labels:
        app: nginx-wait
    spec:
      initContainers:
        - name: wait-for-service
          image: alpine:3.20
          command:
            - sh
            - -c
            - |
              echo "Installing DNS tools..."
              apk add --no-cache bind-tools >/dev/null
              echo "Waiting for DNS name nginx-wait-svc ..."
              until nslookup nginx-wait-svc >/dev/null 2>&1; do
                echo "Service DNS not found yet, sleeping..."
                sleep 2
              done
              echo "Service DNS found!"
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - name: http
              containerPort: 80
